// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjgwsrwkwyxzisvvlfch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ3dzcndrd3l4emlzdnZsZmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTUyNTEsImV4cCI6MjA3MzM3MTI1MX0.kemVeV-36zRnT7rnprollu6NLWBs00KaR-NCVPqoaUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});